name: Google Sheets Telegram Automation

on:
  schedule:
    - cron: '0 16 * * *'  # Runs daily at 16:00 UTC, which is 7 PM EAT
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth
          pip install google-auth==2.30.0
          pip install google-auth-oauthlib==1.2.0
          pip install pandas==2.0.3
          pip install requests
          pip install openpyxl==3.1.3

      - name: Run Python script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          bot_token: "6176422429:AAHEaAA3BCZDFIqL7yZgyZneea1evTkfel8"
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python version5.py
